# Generated by Django 5.1.8 on 2025-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('range_start', models.BigIntegerField(db_index=True)),
                ('range_end', models.BigIntegerField(db_index=True)),
                ('capacity', models.BigIntegerField(blank=True, null=True)),
                ('operator', models.CharField(max_length=255)),
                ('region', models.TextField(max_length=500)),
                ('territory', models.TextField(max_length=500)),
                ('inn', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'range_start', 'range_end'], name='operator_by_code_fd9377_idx')],
            },
        ),
    ]
